# Generated by Django 3.2.5 on 2021-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='cover_images/'),
        ),
    ]
